# Generated by Django 2.2.7 on 2019-11-26 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Цена')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('available', models.BooleanField(default=True, verbose_name='Наличие')),
                ('ingredient', models.ManyToManyField(to='pizza.Ingredient', verbose_name='Ингридиенты')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Size', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Пиццу',
                'verbose_name_plural': 'Пиццы',
                'ordering': ['name'],
            },
        ),
    ]
